Add Rail Delay setting
konikvranik/hacs_rainbird pull request #1
Opened 2021-09-25 21:46 UTC by jhenkens

Hi there!

Happy to have seen you started a migration of the built in Rainbird integration into the config flow, etc. I had that on my todo list mid August, and just got around to it today. Instead, I got to focus on what I wanted to do more - add features.

There's a lot of code change here - tried to clean some things up to follow HA patterns better (serial, rather than hostname, for device_id). 

I also added the ability to get and set the rain-delay feature via a number slider. 

I'm hoping to add the seasonal adjust percentage next. The iPhone app shows a "next watering date", but this isn't exposed in the python API currently - that would be my ultimate goal.

![Screen Shot 2021-09-25 at 2 44 33 PM](https://user-images.githubusercontent.com/242763/134786712-b25b59fe-816b-447a-b926-b43c8c125872.png)

2021-09-25 21:48 UTC, jhenkens commented
Long term, it'd be cool to see if we can clean this up and get it merged into [core](https://github.com/home-assistant/core/) (or have core remove theirs, in favor of the HACS integration).

2021-09-27 21:33 UTC, konikvranik requested changes

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/__init__.py
> +        self._name = "{} {}".format(device_info.get(CONF_NAME), name)
I though about configurable name, but in this case I'd prefer to configure template with the placeholder for number, to allow users to place the number of irrigation circuit anywhere in the name.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/__init__.py
> +        self._unique_id = "{}_{}_{}".format(DOMAIN, data.serial, unique_id)
I'm afraid of stability of this solution. My Rainbird controller often returns 503 ant it is possible, it will not return serial number in time of configurations. So I'd prefer something more stable here.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/translations/en.json
> +          "host": "Hostname or IP of Rainbird controller",
This shouldn't be changed after controller setup

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/__init__.py
> +    rainbird_api = get_rainbird_controller(config_entry.data)
I'd prefer name `rainbird_controller`. API is generally used more in connection with interfaces in programming.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/__init__.py
> +            return "UNKNOWN MODEL"
I think `UNKNOWN` is enough here. But if you want to use longer sentence, what about `Model not detected` or something like this?

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/binary_sensor.py
> +    def __init__(self, hass, controller, device_info, data = None):
I prefer types to be declared. The code is better readable then.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/number.py
> +    def min_value(self):
duplicate entry.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/number.py
> +        self._state = self._controller.get_rain_delay()
we should do all controller calls in separate threads to not block the main thread.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/switch.py
> -    def __init__(self, rb: RainbirdController, device_info: dict, hass: HomeAssistantType,
please keep the types here.

2021-09-27 21:33 UTC, konikvranik commented on custom_components/rainbird/number.py
> +        self._state = self._controller.get_rain_delay()
I though about utilising the service for calling the controller.

2021-09-27 21:47 UTC, konikvranik commented on custom_components/rainbird/config_flow.py
> +            get_rainbird_controller, kwargs
Trying to add new controller, it fails here:
```
  File "hacs_rainbird/custom_components/rainbird/config_flow.py", line 90, in check_serial
    client = await self.hass.async_add_executor_job(
  File "python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "hacs_rainbird/custom_components/rainbird/__init__.py", line 44, in get_rainbird_controller
    retry_sleep=data[CONF_RETRY_DELAY],
KeyError: 'retry_delay'
```

2022-04-04 21:13 UTC, closed without merging